### ISSUE TITLE
Static/dynamic renderable_entities for faster rendering

### ISSUE THREAD

**Issue by texel-sensei** [texel-sensei/eversim#27]
- [x] render_manager register_entity(entity_type)
- [x] two vectors, dynamic and static
- [x] functions to change entities
- [x] dirty flag, if set for dynamic object, reupload
- [x] combine entities via the unique mesh pointers
- [x] make dynamic spritemaps

**Comment by akifreak** [comment]
Merged into develop. Works, but needs additional work for changed static entities
